# run: conda env create --file environment.yml --prefix ./env
name: synmorph
# channels:
    #  - conda-forge
    #  - defaults
dependencies:
  - python=3.9.*
  - numpy=1.*
  - scipy=1.*
  - numba
  - matplotlib=3.4.*
  - conda-forge::tqdm=4.*
  - conda-forge::imageio-ffmpeg
  - conda-forge::firefox
  - conda-forge::geckodriver
  - conda-forge::jupyterlab
  - pip
  - pip:
    - sacred
    - triangle
    - ipywidgets
    - blackcellmagic
        #   - anyio=3.3.4
        #   - appnope=0.1.2
        #   - argon2-cffi=21.1.0
        #   - async_generator=1.10
        #   - attrs=21.2.0
        #   - babel=2.9.1
        #   - backcall=0.2.0
        #   - backports=1.0
        #   - backports.functools_lru_cache=1.6.4
        #   - blas=1.0
        #   - bleach=4.1.0
        #   - brotli=1.0.9
        #   - brotlipy=0.7.0
        #   - bzip2=1.0.8
        #   - ca-certificates=2021.10.8
        #   - certifi=2021.10.8
        #   - cffi=1.14.6
        #   - chardet=4.0.0
        #   - charset-normalizer=2.0.0
        #   - cryptography=35.0.0
        #   - cycler=0.10.0
        #   - debugpy=1.4.1
        #   - decorator=5.1.0
        #   - defusedxml=0.7.1
        #   - entrypoints=0.3
        #   - ffmpeg=4.3.2
        #   - fonttools=4.25.0
        #   - freetype=2.10.4
        #   - gettext=0.19.8.1
        #   - giflib=5.2.1
        #   - gmp=6.2.1
        #   - gnutls=3.6.13
        #   - idna=3.1
        #   - importlib-metadata=4.8.1
        #   - intel-openmp=2021.3.0
        #   - ipykernel=6.4.2
        #   - ipython=7.28.0
        #   - ipython_genutils=0.2.0
        #   - jedi=0.18.0
        #   - jinja2=3.0.2
        #   - jpeg=9d
        #   - json5=0.9.5
        #   - jsonschema=4.1.2
        #   - jupyter_client=7.0.6
        #   - jupyter_core=4.9.0
        #   - jupyter_server=1.11.1
        #   - jupyterlab=3.2.1
        #   - jupyterlab_pygments=0.1.2
        #   - jupyterlab_server=2.8.2
        #   - kiwisolver=1.3.1
        #   - lame=3.100
        #   - lcms2=2.12
        #   - libcxx=12.0.0
        #   - libffi=3.3
        #   - libgfortran=3.0.1
        #   - libiconv=1.16
        #   - libllvm11=11.1.0
        #   - libpng=1.6.37
        #   - libsodium=1.0.18
        #   - libtiff=4.2.0
        #   - libwebp=1.2.0
        #   - libwebp-base=1.2.0
        #   - llvm-openmp=12.0.0
        #   - llvmlite=0.37.0
        #   - lz4-c=1.9.3
        #   - markupsafe=2.0.1
        #   - matplotlib=3.4.3
        #   - matplotlib-base=3.4.3
        #   - matplotlib-inline=0.1.3
        #   - mistune=0.8.4
        #   - mkl=2021.3.0
        #   - mkl-service=2.4.0
        #   - mkl_fft=1.3.1
        #   - mkl_random=1.2.2
        #   - munkres=1.1.4
        #   - nbclassic=0.3.3
        #   - nbclient=0.5.4
        #   - nbconvert=6.2.0
        #   - nbformat=5.1.3
        #   - ncurses=6.2
        #   - nest-asyncio=1.5.1
        #   - nettle=3.6
        #   - notebook=6.4.5
        #   - numba=0.54.1
        #   - numpy=1.20.1
        #   - numpy-base=1.20.1
        #   - olefile=0.46
        #   - openh264=2.1.1
        #   - openssl=1.1.1l
        #   - packaging=21.0
        #   - pandoc=2.15
        #   - pandocfilters=1.5.0
        #   - parso=0.8.2
        #   - pexpect=4.8.0
        #   - pickleshare=0.7.5
        #   - pillow=8.4.0
        #   - pip=21.2.4
        #   - prometheus_client=0.11.0
        #   - prompt-toolkit=3.0.21
        #   - ptyprocess=0.7.0
        #   - pycparser=2.20
        #   - pygments=2.10.0
        #   - pyopenssl=21.0.0
        #   - pyparsing=2.4.7
        #   - pyrsistent=0.17.3
        #   - pysocks=1.7.1
        #   - python=3.9.7
        #   - python-dateutil=2.8.2
        #   - python_abi=3.9
        #   - pytz=2021.3
        #   - pyzmq=22.3.0
        #   - readline=8.1
        #   - requests=2.26.0
        #   - requests-unixsocket=0.2.0
        #   - scipy=1.7.1
        #   - send2trash=1.8.0
        #   - setuptools=58.0.4
        #   - six=1.16.0
        #   - sniffio=1.2.0
        #   - sqlite=3.36.0
        #   - tbb=2021.4.0
        #   - terminado=0.12.1
        #   - testpath=0.5.0
        #   - tk=8.6.11
        #   - tornado=6.1
        #   - traitlets=5.1.1
        #   - tzdata=2021e
        #   - urllib3=1.26.7
        #   - wcwidth=0.2.5
        #   - webencodings=0.5.1
        #   - websocket-client=0.57.0
        #   - wheel=0.37.0
        #   - x264=1!161.3030
        #   - xz=5.2.5
        #   - zeromq=4.3.4
        #   - zipp=3.6.0
        #   - zlib=1.2.11
        #   - zstd=1.4.9
        #   - pip:
        #     - line-profiler==3.3.1
        #     - tqdm==4.62.3
        #     - triangle==20200424
