# run: conda env create --file environment.yml --prefix ./env
name: synmorph
# channels:
    #  - conda-forge
    #  - defaults
dependencies:
  - python=3.9.*
  - numpy>=1.23.*
  - scipy>=1.9.*
  - numba>=0.55.0
  - matplotlib>=3.6.*
  - h5py>=3.*
  - conda-forge::tqdm
  - conda-forge::imageio-ffmpeg
  - conda-forge::firefox
  - conda-forge::geckodriver
  - conda-forge::jupyterlab
  - pip
  - pip:
    - sacred
    - triangle
    - ipywidgets
    - blackcellmagic
    - psutil
    - GitPython
    # - line-profiler
